# Generated by Django 3.2.23 on 2023-12-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_history',
            old_name='latestLocation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='search_history',
            old_name='latestSearch',
            new_name='search',
        ),
    ]
